### PR TITLE
Edited script (thank you angstyfrostyneko for making it btw :))

### PR DESCRIPTION
**Pull request by valflrt**
- Add possibility to set a playlist to add the songs to
- Add logging (displays not found songs for adding by hand afterwards)
- Change variable names from camelCase to snake_case
- Add gitignore (for songlist and database)

### CODE REVIEW

**Comment by valflrt** [comment]
I'm actually adding other things

**Comment by valflrt** [comment]
I'm currently trying to modify the script for:
- selecting a specific search result when no match was automatically found
- searching for videos instead of songs when no song match was found

but I'm running into a problem since the ytmusicapi doesn't work well for getting thumbnails (as you specified...), and it can actually not get a channel's thumbnail...

I might completely rework the script by using another youtube api module.

Don't hesitate to reject the pull request if you don't want your code to be changed !

**Comment by angstyfrostyneko** [comment]
I never expected someone else to use this code, let alone modify it so much lol
I'm impressed with how far you're taking it

And yeah, using another api module is fine, it was the first one I found and I didn't try another

**Comment by valflrt** [comment]
I actually modified it even more on my computer x)
I will upload what I did to my fork soon if you want to see

**Comment by valflrt** [comment]
And btw it was very useful that you added matching for japanese song names

**Comment by angstyfrostyneko** [comment]
Looks really good so far, and by that big comment at the end I'm guessing there's still work to do
It goes without saying, but let me know when you consider its done, I'm looking forward to merging this!

**Comment by valflrt** [comment]
I think it should be working properly, you can merge now if you want.

You should keep the original version of your script in the repository (if I were you I would be a bit sad seeing my script overwritten by a stranger). I hope I didn't make you feel this way :)

**Comment by angstyfrostyneko** [comment]
Awesome! Thanks again :)

**Pull request merged**
